[simulation]
#seed = 102
startdate = 2023-01-30
iterations = 7 # End date; Alternatively, specify the number of iterations
diseasemodel = "../../../../pansim/tests/disease_models/seiar.toml"

[infectionseeding]
perday = 5
days = 7
additional_every_other_days = 3
additional_every_other_days_num = 1
[config]
	activities = ["C:/Users/6997619/Documents/GitHub projects/DHZW-simulation_Sim-2APL/target/classes/DHZW/DHZW_activities_locations.csv"]
	households = ["C:/Users/6997619/Documents/GitHub projects/DHZW-simulation_Sim-2APL/target/classes/DHZW/DHZW_households.csv"]
	persons = ["C:/Users/6997619/Documents/GitHub projects/DHZW-simulation_Sim-2APL/target/classes/DHZW/DHZW_synthetic_population.csv"]