[simulation]
#seed = 102
startdate = 2023-01-30
iterations = 7 # Number of days, or end date

[config]
	activities = ["C:/Users/6997619/Documents/GitHub projects/DHZW-simulation_Sim-2APL/target/classes/DHZW_full/DHZW_activities_locations.csv"]
	households = ["C:/Users/6997619/Documents/GitHub projects/DHZW-simulation_Sim-2APL/target/classes/DHZW_full/DHZW_households.csv"]
	persons = ["C:/Users/6997619/Documents/GitHub projects/DHZW-simulation_Sim-2APL/target/classes/DHZW_full/DHZW_synthetic_population.csv"]
	routing_walk = ["C:/Users/6997619/Documents/GitHub projects/DHZW_routing/output/walk_time_distance.csv"]
	routing_bike = ["C:/Users/6997619/Documents/GitHub projects/DHZW_routing/output/bike_time_distance.csv"]
	routing_car = ["C:/Users/6997619/Documents/GitHub projects/DHZW_routing/output/car_time_distance.csv"]
	routing_bus_tram = ["C:/Users/6997619/Documents/GitHub projects/DHZW_routing/output/routing_bus.csv"]
	routing_train = ["C:/Users/6997619/Documents/GitHub projects/DHZW_routing/output/routing_train.csv"]
	beeline_distance = ["C:/Users/6997619/Documents/GitHub projects/DHZW_routing/output/beeline_distance.csv"]
	output_dir = "C:/Users/6997619/Documents/GitHub projects/DHZW-simulation_Sim-2APL/src/main/resources/sensitivity_analysis/output"