[simulation]
#seed = 102
startdate = 2023-01-30
iterations = 7 # Number of days, or end date

[config]
	activities = ["src/main/resources/DHZW_sample/DHZW_activities_locations_sample.csv"]
	households = ["src/main/resources/DHZW_sample/DHZW_households_sample.csv"]
	persons = ["src/main/resources/DHZW_sample/DHZW_synthetic_population_sample.csv"]
	routing_walk = ["src/main/resources/routing/walk_time_distance.csv"]
	routing_bike = ["src/main/resources/routing/bike_time_distance.csv"]
	routing_car = ["src/main/resources/routing/car_time_distance.csv"]
	routing_bus_tram = ["src/main/resources/routing/routing_bus.csv"]
	routing_train = ["src/main/resources/routing/routing_train.csv"]
	beeline_distance = ["src/main/resources/routing/beeline_distance.csv"]